#!/bin/bash
# Transactional deployment of the generated repository and package policies.
# The entrypoint owns privilege escalation and fixed system paths. Tests call
# the same transaction with explicit fixture paths, without sudo or host writes.

gentoo_path_exists() { [ -e "$1" ] || [ -L "$1" ]; }

gentoo_validate_parent() {
    local parent
    parent="$(dirname "$1")"
    while ! gentoo_path_exists "$parent"; do parent="$(dirname "$parent")"; done
    [ -d "$parent" ] || { echo "Refusing non-directory parent: $parent" >&2; return 1; }
}

gentoo_validate_targets() {
    local target
    if gentoo_path_exists "$repository"; then
        [ ! -L "$repository" ] && [ -d "$repository" ] &&
            [ -f "$repository/.codex-desktop-generated" ] || {
                echo "Refusing unmanaged repository: $repository" >&2; return 1;
            }
    fi
    for target in "$config" "$keywords" "$license"; do
        if gentoo_path_exists "$target"; then
            [ ! -L "$target" ] && [ -f "$target" ] &&
                grep -Fxq "$policy_marker" "$target" || {
                    echo "Refusing unmanaged configuration: $target" >&2; return 1;
                }
        fi
    done
    for target in "$repository" "$config" "$keywords" "$license" "$distfile"; do
        gentoo_validate_parent "$target" || return
    done
    if gentoo_path_exists "$distfile"; then
        [ ! -L "$distfile" ] && [ -f "$distfile" ] &&
            cmp -s "$payload_source" "$distfile" || {
                echo "Refusing conflicting distfile: $distfile" >&2; return 1;
            }
    fi
}

gentoo_transaction_mkdir() {
    local directory="$1"
    if ! gentoo_path_exists "$directory"; then
        gentoo_transaction_mkdir "$(dirname "$directory")"
        mkdir "$directory"
        created_directories+=("$directory")
    fi
}

gentoo_transaction_cleanup() {
    local status="$1" i target backup failed=0
    trap - EXIT HUP INT TERM
    set +e
    if [ "$transaction_committed" -ne 1 ]; then
        for ((i=${#targets[@]}-1; i>=0; i--)); do
            target="${targets[i]}"; backup="${backups[i]:-}"
            # Same-filesystem renames are atomic. A consumed stage means the
            # new target was installed, including signals between mv and $? .
            if [ -n "${stages[i]:-}" ] && ! gentoo_path_exists "${stages[i]}"; then
                rm -rf -- "$target" || failed=1
            fi
            if [ -n "$backup" ] && gentoo_path_exists "$backup/original"; then
                mv -T -- "$backup/original" "$target" || failed=1
            fi
        done
    fi
    # Never delete recovery copies if restoration itself failed.
    for i in "${stages[@]}"; do rm -rf -- "$i"; done
    if [ "$failed" -eq 0 ]; then
        for i in "${backups[@]}"; do rm -rf -- "$i"; done
    else
        printf 'Rollback failed; recovery directories retained: %s\n' "${backups[*]}" >&2
        status=1
    fi
    if [ "$transaction_committed" -ne 1 ]; then
        for ((i=${#created_directories[@]}-1; i>=0; i--)); do
            rmdir -- "${created_directories[i]}" 2>/dev/null || true
        done
    fi
    exit "$status"
}

gentoo_install_transaction() (
    set -Eeuo pipefail
    local source_repository="$1" repository="$2" config="$3" keywords="$4" license="$5"
    local distdir="$6" arch="$7"
    shift 7
    local policy_marker='# Generated by codex-desktop-linux install-gentoo.sh'
    local manifest="$source_repository/app-misc/codex-desktop/Manifest"
    local payload payload_source distfile version lock_directory lock_fd i target parent
    local transaction_committed=0
    local -a ebuilds targets stages=() backups=() created_directories=()

    [ -f "$source_repository/.codex-desktop-generated" ] || {
        echo 'Not a generated codex-desktop repository' >&2; exit 1;
    }
    payload="$(awk '$1 == "DIST" { print $2 }' "$manifest")"
    [[ "$payload" =~ ^codex-desktop-[0-9.]+-(amd64|arm64)-payload-[0-9a-f]{64}\.tar\.xz$ ]] || {
        echo 'Invalid local payload name' >&2; exit 1;
    }
    payload_source="$source_repository/../$payload"
    [ -f "$payload_source" ] || { echo 'Missing local payload archive' >&2; exit 1; }
    shopt -s nullglob
    ebuilds=("$source_repository"/app-misc/codex-desktop/*.ebuild)
    [ "${#ebuilds[@]}" -eq 1 ] || { echo 'Expected exactly one generated ebuild' >&2; exit 1; }
    version="${ebuilds[0]##*/codex-desktop-}"; version="${version%.ebuild}"
    [[ "$version" =~ ^[0-9]+(\.[0-9]+)*$ && "$arch" =~ ^(amd64|arm64)$ ]] || {
        echo 'Invalid Gentoo version or architecture' >&2; exit 1;
    }
    distfile="$distdir/$payload"
    targets=("$repository" "$config" "$keywords" "$license")
    # Every refusal, including policy files and parent types, precedes mkdir,
    # distfile copy, staging, or repository/configuration replacement.
    gentoo_validate_targets
    trap 'gentoo_transaction_cleanup "$?"' EXIT
    trap 'exit 129' HUP
    trap 'exit 130' INT
    trap 'exit 143' TERM

    # Serialize installers without creating a persistent lock file. Recheck
    # under the directory lock before staging any replacement.
    lock_directory="$(dirname "$repository")"
    gentoo_transaction_mkdir "$lock_directory"
    exec {lock_fd}<"$lock_directory"
    flock -x "$lock_fd"
    gentoo_validate_targets
    if ! gentoo_path_exists "$distfile"; then targets+=("$distfile"); fi
    for ((i=0; i<${#targets[@]}; i++)); do
        target="${targets[i]}"; parent="$(dirname "$target")"
        gentoo_transaction_mkdir "$parent"
        if [ "$target" = "$repository" ]; then
            stages[i]="$(mktemp -d "$parent/.codex-desktop-stage.XXXXXX")"
            cp -a --no-preserve=ownership "$source_repository/." "${stages[i]}/"
            chmod -R u=rwX,go=rX "${stages[i]}"
        else
            stages[i]="$(mktemp "$parent/.codex-desktop-stage.XXXXXX")"
            case "$target" in
                "$config") printf '%s\n[codex-desktop-local]\nlocation = %s\nmasters = gentoo\nauto-sync = no\n' "$policy_marker" "$repository" > "${stages[i]}" ;;
                "$keywords") printf '%s\napp-misc/codex-desktop::codex-desktop-local ~%s\n' "$policy_marker" "$arch" > "${stages[i]}" ;;
                "$license") printf '%s\napp-misc/codex-desktop::codex-desktop-local all-rights-reserved\n' "$policy_marker" > "${stages[i]}" ;;
                "$distfile") cp "$payload_source" "${stages[i]}" ;;
            esac
            chmod 0644 "${stages[i]}"
        fi
    done
    for ((i=0; i<${#targets[@]}; i++)); do
        target="${targets[i]}"
        if gentoo_path_exists "$target"; then
            backups[i]="$(mktemp -d "$(dirname "$target")/.codex-desktop-backup.XXXXXX")"
            mv -T -- "$target" "${backups[i]}/original"
        fi
        mv -T -- "${stages[i]}" "$target"
    done
    "$@" "=app-misc/codex-desktop-$version::codex-desktop-local"
    transaction_committed=1
)
